function p225stellahyp = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  P225STELLAHYP = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  P225STELLAHYP = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  p225stellahyp = importfile1("C:\Users\ninal\OneDrive - University of Edinburgh\University\Postgrad\Research\Research_Projects\ASR_Bias\VCTK-Corpus\VCTK-Corpus\UK_Ireland\stella\ASR\google_enGB\p225_stella_hyp.trn.dtl", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Jul-2021 09:23:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 45);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["With", "Var2", "Var3", "Var4", "occurrences", "Var6", "Var7", "Var8", "VarName9", "VarName10", "VarName11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45"];
opts.SelectedVariableNames = ["With", "occurrences", "VarName9", "VarName10", "VarName11"];
opts.VariableTypes = ["categorical", "string", "string", "string", "double", "string", "string", "string", "string", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "VarName9", "VarName11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["With", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "VarName9", "VarName10", "VarName11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "occurrences", "TrimNonNumeric", true);
opts = setvaropts(opts, "occurrences", "ThousandsSeparator", ",");

% Import the data
p225stellahyp = readtable(filename, opts);

% Delete rows we don't need

% look for the confusion pair section: 
confstart=find(strcmp(string(p225stellahyp.With), 'CONFUSION')); 
insstart = find(strcmp(string(p225stellahyp.With), 'INSERTIONS')); 
delstart = find(strcmp(string(p225stellahyp.With), 'DELETIONS')); 
substart = find(strcmp(string(p225stellahyp.With), 'SUBSTITUTIONS')); 
subend = find(strcmp(string(p225stellahyp.With), 'FALSELY')); 

indexdelete = [1:confstart-1];

p225stellahyp(indexdelete, :) = []






end